### ISSUE TITLE
Steam pipe db start fails for certain Linux configurations

### ISSUE THREAD

**Issue by thapabishwa** [turbot/steampipe#133]
```
~ >>> steampipe service start                                                                                                          
panic: x Download & install embedded PostgreSQL database... FAILED! error moving file: rename /tmp/us-docker.pkg.dev_steampipe_steampipe_db@12.1.0-v2/extracted-linux-amd64-12.1.0-1/share /home/bishwa/.steampipe/db/12.1.0/postgres/share: invalid cross-device link

goroutine 1 [running]:
github.com/turbot/steampipe/utils.FailOnErrorWithMessage(0xff1fc0, 0xc000152e40, 0xe8ccc3, 0x3c)
	/home/runner/work/steampipe/steampipe/utils/errors.go:28 +0x137
github.com/turbot/steampipe/db.EnsureDBInstalled()
	/home/runner/work/steampipe/steampipe/db/install.go:76 +0xb79
github.com/turbot/steampipe/cmd.runServiceStartCmd(0xc000347b80, 0x16a88d8, 0x0, 0x0)
	/home/runner/work/steampipe/steampipe/cmd/service.go:138 +0x325
github.com/turbot/steampipe/cmdconfig.OnCmd.func1(0xc000347b80, 0x16a88d8, 0x0, 0x0)
	/home/runner/work/steampipe/steampipe/cmdconfig/builder.go:30 +0x65
github.com/spf13/cobra.(*Command).execute(0xc000347b80, 0x16a88d8, 0x0, 0x0, 0xc000347b80, 0x16a88d8)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x166ff60, 0x1, 0x1, 0xc00037be60)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/turbot/steampipe/cmd.Execute(0xc00037be60, 0x1)
	/home/runner/work/steampipe/steampipe/cmd/root.go:53 +0x6d
main.main()
	/home/runner/work/steampipe/steampipe/main.go:27 +0x8e
~ >>>                                                               
```

**Comment by binaek89** [comment]
@thapabishwa thank you for reporting the issue. We will take a look into it. It would be great if you could give us what environment (OS,FileSystem, etc.) you are running `steampipe` in.

**Comment by shamil** [comment]
Same issue. I'm on linux. my `/tmp` and `/home` directories are separate partitions. Maybe this is related.

**Comment by e-gineer** [comment]
I believe the problem is that [we are using `os.Rename`](https://github.com/turbot/steampipe/blob/4b28072d02a1d7fb130088581b9d63877fffcc5f/ociinstaller/zip.go#L167), which [does not allow copying files across partitions](https://github.com/golang/go/issues/13766).

We should move to using `~/.steampipe/tmp` or similar instead of `/tmp`, which would avoid this issue.

Thanks to @thapabishwa and @shamil for reporting.
