### ISSUE TITLE
Crash when ctrl+c exiting from dashboard command

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#1952]
Steampipe v0.14.0-alpha.13

```
[ Wait    ] Dashboard execution started: aws_compliance.benchmark.foundational_security
^Cpanic: send on closed channel
	panic: send on closed channel

goroutine 18720 [running]:
github.com/turbot/steampipe/workspace.(*Workspace).PublishDashboardEvent(0x101402e20?, {0x1016045b8?, 0x1400088e480?})
	/Users/mike/Code/github.com/turbot/steampipe/workspace/workspace_events.go:17 +0x38
panic({0x101478de0, 0x1016024d0})
	/usr/local/go/src/runtime/panic.go:838 +0x204
github.com/turbot/steampipe/workspace.(*Workspace).PublishDashboardEvent(...)
	/Users/mike/Code/github.com/turbot/steampipe/workspace/workspace_events.go:17
github.com/turbot/steampipe/dashboard/dashboardexecute.(*CheckRun).SetComplete(0x1400195c000)
	/Users/mike/Code/github.com/turbot/steampipe/dashboard/dashboardexecute/check_run.go:135 +0x128
github.com/turbot/steampipe/dashboard/dashboardexecute.(*CheckRun).Execute(0x1400195c000, {0x10160feb0, 0x14002db3180})
	/Users/mike/Code/github.com/turbot/steampipe/dashboard/dashboardexecute/check_run.go:95 +0xcc
github.com/turbot/steampipe/dashboard/dashboardexecute.(*DashboardExecutionTree).Execute(0x1400088e3f0, {0x10160ff58, 0x1400068ff20})
	/Users/mike/Code/github.com/turbot/steampipe/dashboard/dashboardexecute/dashboard_execution_tree.go:126 +0x500
created by github.com/turbot/steampipe/dashboard/dashboardexecute.(*DashboardExecutor).ExecuteDashboard
	/Users/mike/Code/github.com/turbot/steampipe/dashboard/dashboardexecute/executor.go:61 +0x1dc
```

**Comment by kaidaguerre** [comment]
fixed by 12bdf623116a9a5c2dac06f205d9fbffba6ff207
