### ISSUE TITLE
Intermittent "send on closed channel" panic when trying to exit dashboard process

### ISSUE THREAD

**Issue by MichaelBurgess** [turbot/steampipe#2347]
**Describe the bug**
Occasionally when trying to exit the dashboard process, you get a "send on closed channel" panic like this:

```
^Cpanic: send on closed channel

goroutine 12567 [running]:
github.com/turbot/steampipe/pkg/workspace.(*Workspace).PublishDashboardEvent(...)
	/Users/mike/Code/github.com/turbot/steampipe/pkg/workspace/workspace_events.go:18
github.com/turbot/steampipe/pkg/dashboard/dashboardexecute.(*DashboardExecutionTree).Execute(0x14001bfc5a0, {0x10221fac8, 0x14000878e70})
	/Users/mike/Code/github.com/turbot/steampipe/pkg/dashboard/dashboardexecute/dashboard_execution_tree.go:102 +0x1b4
created by github.com/turbot/steampipe/pkg/dashboard/dashboardexecute.(*DashboardExecutor).ExecuteDashboard
	/Users/mike/Code/github.com/turbot/steampipe/pkg/dashboard/dashboardexecute/executor.go:58 +0x1bc
```

**Steampipe version (`steampipe -v`)**
Example: >= `v0.15.x`

**To reproduce**
Run a dashboard process and run some dashboards, then try to stop the process with Ctrl-C.

**Expected behavior**
The dashboard process exits cleanly.

**Comment by kaidaguerre** [comment]
fixed by https://github.com/turbot/steampipe/commit/962ac0445a4f20d7722b813bed86db6ef667f30c
