### ISSUE TITLE
Connecting to 0.21 server from a 0.20 client in interactive panics 

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe#3931]
only interactive fails 
```
➜  ~ /opt/homebrew/bin/steampipe query --workspace-database postgres://steampipe@127.0.0.1:9193/steampipe
Welcome to Steampipe v0.20.12
For more information, type .help
> panic: runtime error: index out of range [0] with length 0

goroutine 15 [running]:
github.com/turbot/steampipe/pkg/db/db_local.getLocalSteampipeConnectionString(0x1039cfc2c?)
	/home/runner/work/steampipe/steampipe/pkg/db/db_local/create_connection.go:52 +0x5e8
github.com/turbot/steampipe/pkg/db/db_local.CreateLocalDbConnection({0x1043b4360, 0x140003c6980}, 0x14000e6e000?)
	/home/runner/work/steampipe/steampipe/pkg/db/db_local/create_connection.go:82 +0x64
github.com/turbot/steampipe/pkg/interactive.(*InteractiveClient).getNotificationConnection(0x103a0364f?, {0x1043b4360, 0x140003c6980})
	/home/runner/work/steampipe/steampipe/pkg/interactive/interactive_client.go:747 +0x58
github.com/turbot/steampipe/pkg/interactive.(*InteractiveClient).listenToPgNotifications(0x14000c143c0?, {0x1043b4360, 0x140003c6980})
	/home/runner/work/steampipe/steampipe/pkg/interactive/interactive_client.go:718 +0x50
created by github.com/turbot/steampipe/pkg/interactive.(*InteractiveClient).readInitDataStream
	/home/runner/work/steampipe/steampipe/pkg/interactive/interactive_client_init.go:130 +0x2c8
➜  ~ 
➜  ~ 
➜  ~ /opt/homebrew/bin/steampipe query --workspace-database postgres://steampipe@127.0.0.1:9193/steampipe "select account_id from aws_account"
+--------------+
| account_id   |
+--------------+
| 453319552164 |
+--------------+
➜  ~ 


```

**Comment by pskrbasu** [comment]
https://github.com/turbot/steampipe/pull/3933
