### ISSUE TITLE
interactive prompt rendering crashes for extremely small console size

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/steampipe#894]
I see this in goland but not in iterm

![image](https://user-images.githubusercontent.com/2838960/133071427-b3f8853b-9c3e-4764-b554-9800c0d1f718.png)

```
goroutine 142 [running]:
github.com/turbot/steampipe/interactive.(*InteractiveClient).runInteractivePrompt.func1(0xc000549fa0)
        /Users/kai/Dev/github/turbot/steampipe/interactive/interactive_client.go:205 +0x9a
panic(0x4e0b540, 0xc000636330)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/c-bata/go-prompt.(*Render).renderCompletion(0xc00039e460, 0xc000594240, 0xc00068a0c0, 0xfffffffffffffffe)
        /Users/kai/Dev/go/pkg/mod/github.com/turbot/go-prompt@v0.2.6-steampipe.0.20210830083819-c872df2bdcc9/render.go:129 +0xd0e
github.com/c-bata/go-prompt.(*Render).Render(0xc00039e460, 0xc000594240, 0x0, 0x0, 0xc00068a0c0)
        /Users/kai/Dev/go/pkg/mod/github.com/turbot/go-prompt@v0.2.6-steampipe.0.20210830083819-c872df2bdcc9/render.go:249 +0x6aa
github.com/c-bata/go-prompt.(*Prompt).RunCtx(0xc0009ae1e0, 0x5120840, 0xc000594000)
        /Users/kai/Dev/go/pkg/mod/github.com/turbot/go-prompt@v0.2.6-steampipe.0.20210830083819-c872df2bdcc9/prompt.go:125 +0x717
github.com/turbot/steampipe/interactive.(*InteractiveClient).runInteractivePrompt(0xc000423a00, 0x5120840, 0xc000594000, 0x0)
        /Users/kai/Dev/github/turbot/steampipe/interactive/interactive_client.go:304 +0x94a
github.com/turbot/steampipe/interactive.(*InteractiveClient).runInteractivePromptAsync.func1(0xc000116010, 0xc000423a00, 0x5120840, 0xc000594000)
        /Users/kai/Dev/github/turbot/steampipe/interactive/interactive_client.go:183 +0x3f
created by github.com/turbot/steampipe/interactive.(*InteractiveClient).runInteractivePromptAsync
        /Users/kai/Dev/github/turbot/steampipe/interactive/interactive_client.go:182 +0x5d
```

**Comment by binaek** [comment]
Fixed by https://github.com/turbot/go-prompt/commit/86fb3afc968edb1dd580880478a5fbd5c8a9474b
